# Generated by Django 5.2.6 on 2026-01-03 04:31

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=100)),
                ('sales_contact', models.CharField(max_length=100)),
                ('apply_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('billing_start_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('parent_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='netbox_rms.serviceorder')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '业务主工单',
                'verbose_name_plural': '业务主工单',
                'ordering': ['-apply_date', '-pk'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('task_type', models.CharField(default='allocation', max_length=50)),
                ('lifecycle_status', models.CharField(default='draft', max_length=50)),
                ('execution_status', models.CharField(default='pending', max_length=50)),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('bandwidth', models.CharField(blank=True, max_length=50)),
                ('protection', models.BooleanField(default=False)),
                ('protection_type', models.CharField(blank=True, max_length=50)),
                ('interface_type', models.CharField(blank=True, max_length=50)),
                ('site_a', models.CharField(blank=True, max_length=255)),
                ('site_z', models.CharField(blank=True, max_length=255)),
                ('circuit_id', models.CharField(blank=True, max_length=100)),
                ('dev_model_a', models.CharField(blank=True, max_length=100)),
                ('slot_a', models.CharField(blank=True, max_length=50)),
                ('port_a', models.CharField(blank=True, max_length=50)),
                ('dev_model_z', models.CharField(blank=True, max_length=100)),
                ('slot_z', models.CharField(blank=True, max_length=50)),
                ('port_z', models.CharField(blank=True, max_length=50)),
                ('config_status', models.BooleanField(default=False)),
                ('test_status', models.BooleanField(default=False)),
                ('cable_core', models.CharField(blank=True, max_length=50)),
                ('odf_pos', models.CharField(blank=True, max_length=100)),
                ('jump_status', models.BooleanField(default=False)),
                ('ext_resource', models.BooleanField(default=False)),
                ('ext_contract', models.CharField(blank=True, max_length=100)),
                ('device_brand', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('power_rating', models.CharField(blank=True, max_length=50)),
                ('rack_u_pos', models.CharField(blank=True, max_length=50)),
                ('power_status', models.BooleanField(default=False)),
                ('change_types', models.JSONField(blank=True, default=list)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ext_handle', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='netbox_rms.serviceorder')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '执行任务详情',
                'verbose_name_plural': '执行任务详情',
                'ordering': ['-pk'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('lifecycle_status', models.CharField(default='active', max_length=50)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='netbox_rms.serviceorder')),
            ],
            options={
                'verbose_name': '资源台账',
                'verbose_name_plural': '资源台账',
                'ordering': ['-pk'],
                'unique_together': {('resource_type', 'resource_id')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
