# Generated by Django 5.2.6 on 2026-01-04 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0001_initial'),
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='tenant',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='tenancy.tenant'),
            preserve_default=False,
        ),
    ]
