# Generated by Django 5.2.6 on 2026-01-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0002_remove_serviceorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='business_manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='internal_participants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
