# Generated by Django 5.2.6 on 2026-01-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0003_serviceorder_business_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='internal_participants',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='internal_participant',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
