# Generated by Django 5.2.6 on 2026-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0004_remove_serviceorder_internal_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='check_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='check_result',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='check_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='unavailable_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
