# Generated by Django 5.2.6 on 2026-01-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0005_add_resource_check_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-created'], 'permissions': [('check_serviceorder', '可以填写核查结果')]},
        ),
    ]
