# Generated by Django 5.2.6 on 2026-01-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0006_alter_serviceorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-apply_date', '-pk'], 'permissions': (('can_check_resource', 'Can edit resource check fields'),)},
        ),
    ]
