# Generated by Django 5.2.6 on 2026-01-06 00:13

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_rms', '0007_alter_serviceorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-apply_date', '-pk']},
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='check_result',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='unavailable_reasons',
        ),
        migrations.CreateModel(
            name='ResourceCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('check_result', models.CharField(blank=True, max_length=50)),
                ('unavailable_reasons', models.JSONField(blank=True, default=list)),
                ('comments', models.TextField(blank=True)),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_result_obj', to='netbox_rms.serviceorder')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '资源核查结果',
                'verbose_name_plural': '资源核查结果',
                'ordering': ['-pk'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
