# Generated by Django 5.2.6 on 2026-01-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0008_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='project_code',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='confirmation_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='contract_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='project_approval_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='project_report_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
