# Generated by Django 5.2.6 on 2026-01-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0009_remove_serviceorder_project_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='start_date',
        ),
    ]
