# Generated by Django 5.2.6 on 2026-01-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0010_remove_serviceorder_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcecheckresult',
            old_name='comments',
            new_name='description',
        ),
    ]
