# Generated by Django 5.2.6 on 2026-01-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0014_migrate_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='task_type',
            field=models.CharField(default='activation', max_length=50),
        ),
    ]
