# Generated by Django 5.2.6 on 2026-01-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0015_alter_taskdetail_task_type'),
        ('netbox_rms', '0015_remove_lifecycle_status'),
    ]

    operations = [
    ]
