# Generated by Django 5.2.6 on 2026-01-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_rms', '0017_taskdetail_execution_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='feedback_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
